#!/bin/bash

# This file is useful for development purposes because
# it allows you to run TypeScript files without having
# to add the --loader option every time.

# Usage:

# ./node --version
# ./node bin/main.ts
# ./node --inspect bin/artisan.ts

# Usage with "sh" or "bash":

# sh node --version
# sh node bin/main.ts
# sh node --inspect bin/artisan.ts

# Node.js executable with all arguments required to run the application.
node="node --loader=ts-node/esm --experimental-import-meta-resolve --no-warnings"

# Replace the first occurrence of "artisan" with "bin/artisan.ts",
# including any preceding or following spaces.
args=$(echo "$@" | sed -E 's/(^| )artisan( |$)/ \1bin\/artisan.ts\2/')

# Execute Node.js with the modified arguments.
$node $args
