version: "3"

services:
  postgres:
    container_name: athenna_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
